plugin: aws_ec2
regions:
  - ap-south-1

hostnames: 
  - public_dns_name
  
keyed_groups:
  - key: tags.Name
    prefix: tag

#filters:
  #tag:Name: infra_server

#compose:
  #ansible_host: public_ip_address

  

